### ISSUE TITLE
Plugin breaks if ruff config contains `fix = true`

### ISSUE THREAD

**Issue by Daverball** [kaste/SublimeLinter-contrib-ruff#1]
https://github.com/kaste/SublimeLinter-contrib-ruff/blob/e7b70fcf41c6bcee5c2992e4831ab9063eea1f2f/linter.py#L27

I would suggest extending the command with `--no-fix` to ensure that the plugin still works even if a project contains a ruff config that is setup for something like pre-commit where it's always expected to apply autofixes. Otherwise it will crash when trying to parse the output as JSON, since the output first contains the fixed file and then the JSON output.

**Comment by kaste** [comment]
Thanks for reporting.  Wasn't aware of the `--no-fix` option.
